### ISSUE TITLE
Other language libraries

### ISSUE THREAD

**Issue by e-shirt** [Holenstein-Ingenieure-AG/lrs-editor#2]
Documentation states that there are more language libraries available but I cannot find an option to change that for the plugin nor does it change with QGIS system locale. Are other languages closed source?

**Comment by meier-r** [comment]
The plugin is only in English available, no other languages are at the moment implemented. Because the plugin ist quite new, implementing other languages is still pending and depends also on further interest and use of the plugin. In a next step the plugin would surely be implemented in German language.
